spring:
  application:
    name: EMAIL-CONFIG  
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MahiSt/mail-service  
eureka: 
  client: 
    serrvice-url: 
      default-zone: http://EUREKA-REGISTRY
  
    