eureka: 
 instance: 
   hostname: ${host}

 client: 
   service-url: 
     default-zone: http://${eureka.instance.hostname}:${server.port}

   fetch-registry: false 
   register-with-eureka: false 

 server:
   enable-self-preservation: false 

spring:
  application:
    name: EUREKA-REGISTRY       