spring:
  application:
    name: EMAIL-API 
  config:
#    import: "optional:configserver:" #if the config server is running in 8888 this will work fine
    import: configserver:http://${configserverhost}:${configport}
    